package net.coremc.skyblock.spawners.spawner;

import org.bukkit.Material;
import org.bukkit.configuration.ConfigurationSection;

import java.util.Locale;

/**
 * A single configurable drop row for a mob variant.
 *
 * <p>All values are read from config so balancing never requires a recompile:</p>
 * <ul>
 *   <li>{@code material} – the vanilla item dropped (no custom items are created).</li>
 *   <li>{@code min}/{@code max} – inclusive amount range rolled per kill.</li>
 *   <li>{@code chance} – 0..1 probability the drop is rolled at all.</li>
 *   <li>{@code sell} – per-unit player sell value (money).</li>
 *   <li>{@code core} – per-unit island Core contribution generated by the drop.</li>
 *   <li>{@code tokens} – per-unit Sky Tokens granted to the killer.</li>
 * </ul>
 */
public final class DropEntry {

    private final Material material;
    private final int min;
    private final int max;
    private final double chance;
    private final double sell; // per-unit player money value
    private final double core; // per-unit island Core contribution
    private final long tokens;  // per-unit Sky Tokens

    public DropEntry(final Material material, final int min, final int max,
                     final double chance, final double sell, final double core, final long tokens) {
        this.material = material;
        this.min = min;
        this.max = Math.max(min, max);
        this.chance = chance;
        this.sell = sell;
        this.core = core;
        this.tokens = tokens;
    }

    public static DropEntry load(final ConfigurationSection sec) {
        final Material mat = safeMat(sec.getString("material", "AIR"));
        final int min = Math.max(0, sec.getInt("min", 1));
        final int max = Math.max(min, sec.getInt("max", min));
        final double chance = sec.getDouble("chance", 1.0);
        final double sell = sec.getDouble("sell", 0.0);
        final double core = sec.getDouble("core", 0.0);
        final long tokens = sec.getLong("tokens", 0);
        return new DropEntry(mat, min, max, chance, sell, core, tokens);
    }

    private static Material safeMat(final String s) {
        if (s == null) {
            return Material.AIR;
        }
        try {
            return Material.valueOf(s.toUpperCase(Locale.ROOT));
        } catch (final IllegalArgumentException e) {
            return Material.AIR;
        }
    }

    public Material material() { return material; }
    public int min() { return min; }
    public int max() { return max; }
    public double chance() { return chance; }
    public double sell() { return sell; }
    public double core() { return core; }
    public long tokens() { return tokens; }

    /** Roll this drop. Returns the amount to grant (0 when it does not drop). */
    public int rollAmount(final java.util.Random rnd) {
        if (material == Material.AIR) {
            return 0;
        }
        if (chance <= 0.0) {
            return 0;
        }
        if (chance < 1.0 && rnd.nextDouble() > chance) {
            return 0;
        }
        if (max <= min) {
            return min;
        }
        return min + rnd.nextInt(max - min + 1);
    }

    /** Total player money value if {@code amount} of this drop are produced. */
    public double moneyValue(final int amount) { return sell * amount; }

    /** Total island Core contribution if {@code amount} of this drop are produced. */
    public double coreValue(final int amount) { return core * amount; }

    /** Total Sky Tokens if {@code amount} of this drop are produced. */
    public long tokenValue(final int amount) { return tokens * amount; }
}
