package net.coremc.skyblock.islandcore;

/**
 * Island-buff hooks for the Core system.
 *
 * <p>This is the contract future island-buff sources implement. The Core service
 * only multiplies configured base values through these methods — it does NOT
 * implement a buff system of its own. If no buff provider is registered, every
 * method returns its identity value (1.0 multiplier / 0 bonus), so the Core
 * foundation works standalone and upgrades cleanly when buffs arrive.</p>
 *
 * <p>Register a provider via {@link CoreService#setBuffApi(CoreBuffApi)}.</p>
 */
public interface CoreBuffApi {

    /** Multiplier applied to Core money earned per action (1.0 = none). */
    default double coreMoneyMultiplier(final int islandId) { return 1.0; }

    /** Multiplier applied to the drop sell value (1.0 = none). */
    default double sellMultiplier(final int islandId) { return 1.0; }

    /** Multiplier applied to Sky Tokens generated by Core activity (1.0 = none). */
    default double skyTokenMultiplier(final int islandId) { return 1.0; }

    /** Generic extra multiplier for any other Core-related quantity (1.0 = none). */
    default double genericMultiplier(final int islandId) { return 1.0; }
}
