package net.coremc.skyblock.islandcore;

import org.bukkit.entity.Player;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.UUID;

/**
 * Immutable description of a single Core contribution request.
 *
 * <p>Built with {@link #builder(int, UUID, CoreAction)}. The Core service reads
 * the <i>base</i> values from here; island buffs and live events multiply them
 * before they are persisted. {@code kills} already includes the variant
 * progression multiplier (e.g. 3 for an Ancient mob) so the actual kill count
 * stays accurate while progression accelerates.</p>
 */
public final class CoreContributionContext {

    public final int islandId;
    public final @NotNull UUID playerId;
    public final @NotNull CoreAction action;
    public final @NotNull String source;       // spawnerId, or "mining" / "farming" / ...
    public final double baseMoney;             // configured Core money for this action (fractional)
    public final double baseTokens;            // configured Sky Tokens for this action
    public final long kills;                   // progression added (already variant-scaled)
    public final double sellValue;             // sell value of drops generated by this action
    public final @Nullable String variantId;   // variant id if this is a mob kill
    public final @Nullable Player player;      // nullable (offline / aggregate)
    public final boolean applyEventMultipliers;

    private CoreContributionContext(final Builder b) {
        this.islandId = b.islandId;
        this.playerId = b.playerId;
        this.action = b.action;
        this.source = b.source;
        this.baseMoney = b.baseMoney;
        this.baseTokens = b.baseTokens;
        this.kills = b.kills;
        this.sellValue = b.sellValue;
        this.variantId = b.variantId;
        this.player = b.player;
        this.applyEventMultipliers = b.applyEventMultipliers;
    }

    public static Builder builder(final int islandId, final @NotNull UUID playerId, final @NotNull CoreAction action) {
        return new Builder(islandId, playerId, action);
    }

    public static final class Builder {
        final int islandId;
        final @NotNull UUID playerId;
        final @NotNull CoreAction action;
        String source = "other";
        double baseMoney = 0;
        double baseTokens = 0;
        long kills = 0;
        double sellValue = 0;
        String variantId = null;
        Player player = null;
        boolean applyEventMultipliers = true;

        Builder(final int islandId, final @NotNull UUID playerId, final @NotNull CoreAction action) {
            this.islandId = islandId;
            this.playerId = playerId;
            this.action = action;
        }

        public Builder source(final String s) { this.source = s; return this; }
        public Builder baseMoney(final double v) { this.baseMoney = v; return this; }
        public Builder baseTokens(final double v) { this.baseTokens = v; return this; }
        public Builder kills(final long v) { this.kills = v; return this; }
        public Builder sellValue(final double v) { this.sellValue = v; return this; }
        public Builder variantId(final String v) { this.variantId = v; return this; }
        public Builder player(final Player p) { this.player = p; return this; }
        public Builder applyEventMultipliers(final boolean b) { this.applyEventMultipliers = b; return this; }

        public CoreContributionContext build() { return new CoreContributionContext(this); }
    }
}
