package net.coremc.skyblock.events;

/**
 * The category of reward a live event multiplies.
 *
 * <p>Every configured event maps to exactly one of these. The manager exposes a
 * typed multiplier per category so existing systems query the active event by
 * category instead of re-implementing the schedule. New event categories are added
 * here (and given an integration point) without touching the rotation/scheduling
 * logic.</p>
 */
public enum GameEventType {

    /** Multiplies shared island XP awarded via {@code ProgressionApi#awardIslandXp}. */
    ISLAND_XP,

    /** Multiplies the SLAYING role currency ("Slaying Coins") earned by the Slaying Omnitool. */
    SLAYING_COINS,

    /** Multiplies per-Omnitool tool XP + role currency earned by any Omnitool. */
    OMNITOOL_PROGRESS,

    /** Multiplies Core money + progression contribution from island activity. */
    CORE_CONTRIBUTION,

    /** Multiplies mob-unlock progression (kills credited toward unlocks). */
    CORE_PROGRESSION,

    /** Multiplies Sky Tokens generated by Core activity. */
    CORE_TOKENS,

    /** Multiplies the sell value of Core drops / activity. */
    CORE_SELL,

    /**
     * Catch-all for future event types (Set XP, Mob Drops, Farming/Mining/Fishing XP,
     * Boss events, Community events, ...). The framework still rotates and displays
     * them; the multiplier is exposed generically and consumed by the relevant
     * future integration point.
     */
    OTHER;

    /**
     * Resolve a config string to a type, defaulting to {@link #OTHER} for unknown
     * values so a typo in config never breaks the rotation.
     */
    public static GameEventType from(final String raw) {
        if (raw == null) return OTHER;
        try {
            return GameEventType.valueOf(raw.trim().toUpperCase(java.util.Locale.ROOT));
        } catch (final IllegalArgumentException e) {
            return OTHER;
        }
    }
}
